### ISSUE TITLE
关于训练集，特征和结果怎么区分

### ISSUE THREAD

**Issue by xiaohaoxh** [ineedahouse/top-algorithm-set#1]
谢谢大佬！

**Comment by ineedahouse** [comment]
BP神经网络的特征截取训练集的[0,inputCount)列，结果截取训练集的[inputCount,outputCount)列
其中inputCount为输入层神经元个数，outputCount为输出层神经元个数，若训练集的列数不等于inputCount与outputCount的和，就会抛出异常。
例：训练集为100行5列的矩阵，即trainSet[100][5]，输入层神经元为4，输出层神经元为1，则特征矩阵的前4列为特征，第4到第5列为结果标签。
注：若不设置输入层神经元个数，则默认为3，输出层神经元个数默认为1，由于训练集的列数可能不为4，就会报错，这个问题会在下个版本解决。建议创建参数对象时，设置好各参数。

**Comment by amace-lzo** [comment]
> 谢谢大佬！

BP神经网络的特征截取训练集的`[0,inputCount)`列，结果截取训练集的`[inputCount,outputCount)`列
其中`inputCount`为输入层神经元个数，`outputCount`为输出层神经元个数，若训练集的列数不等于`inputCount`与`outputCount`的和，就会抛出异常。
**例**：训练集为100行5列的矩阵，即`trainSet[100][5]`，输入层神经元为4，输出层神经元为1，则训练集的前4列为特征，第4到第5列为结果标签。
**注**：若不设置输入层神经元个数，则默认为3，输出层神经元个数默认为1，由于训练集的列数可能不为4，就会报错，这个问题会在下个版本解决。建议创建参数对象时，设置好各参数。
