### ISSUE TITLE
想请问下bp算法相关知识跟代码中的数据集

### ISSUE THREAD

**Issue by HHubbert** [ineedahouse/top-algorithm-set#2]
作者您好，目前小白在学习BP相关知识，可以请问一下在测试bpnmTest.java中的trainData.csv里面的数据集内容是怎样的，感谢！
还有想请教一个问题，如果输入值和输出值如果不为数值，不知道能否使用该算法。例如想通过许多部电影得出用户预期想看的电影，然后在通过这个算法将用户实际想看的电影进行bp算法反向传播重新设置权重，不知道这个功能能否通过bp算法进行实现，如果可以的话，那么请问这个输入值和输出值应该怎么设置呢？感谢！

**Comment by amace-lzo** [comment]
trainData.csv链接https://github.com/ineedahouse/top-algorithm-set-doc/blob/master/doc/bpnn/trainData.csv
你这种情况属于推荐系统，我觉得不适合用BP，通过很多电影来预测出用户想看的电影，首先你想，电影和电影之间是没有直接关系的，电影之间是间接关系，比如电影-类别（或特征）-电影，这样你指输入电影，系统没有类别或特征信息，怎么给你推荐电影，另外一个重要的点是，你输入ABC三个电影想要系统输出D，这个D是从哪里来呢？凭空预测出来的吗？当你想通这两个点时，就知道这种情况不适合BP神经网络了，这只是我个人的观点，如果你有不同的观点或者解决方案，可以一起讨论。你可以使用基于协同过滤的推荐算法，推荐你一本书图灵系列的《推荐系统实践》。

**Comment by HHubbert** [comment]
感谢作者！
