### ISSUE TITLE
动量项计算问题

### ISSUE THREAD

**Issue by liangjiayy** [ineedahouse/top-algorithm-set#3]
com.top.bpnn包下的BPNeuralNetworkFactory类中，计算动量项的时候，感觉少乘了一个（1-momentumFactor）：

![image](https://user-images.githubusercontent.com/96457963/160236398-49df2598-e2fa-4c4a-840b-e4a2c8f6b8d4.png)
公式是：
![image](https://user-images.githubusercontent.com/96457963/160236475-da697b20-17ff-423d-836e-da89d6b7bd2c.png)

**Comment by amace-lzo** [comment]
[Hameed, Alaa Ali, Bekir Karlik, and Mohammad Shukri Salman. "Back-propagation algorithm with variable adaptive momentum." Knowledge-Based Systems 114 (2016): 79-87.](https://d1wqtxts1xzle7.cloudfront.net/53008911/bp_kbs-with-cover-page-v2.pdf?Expires=1648476850&Signature=J7bwztEqokT~pRGO0oA-uhcg9~lCbliHv7FOFHDFXpAo2zVHkBYPExwEG4hO4Xlg1zpfzHWyo2sw0RVH1UaavKVycsisXOgPzlSLcitIbHr~B0xM4MJNJR5qXxwQCaNr7iuYfdMHWoglDQZ6uboaIUYIe-AFDRNf0uvx6TBKUEl95nusISm~fl9JP~lovaZFenAUd6HXK6ajn9Wb9R99B3RTe7ca2NlsokTZ5pdgePT9~YXo0gi7UO~im4i6JTXM70zo51dKOpTafOuF5dnZUiPUK4cH-cAnvO1MiwbCi0AcP6UeqOqUcWvn51QLhbqZMO-6oZ9mtfYkkoVvHTTmPg__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA)
[Wu, Wei, et al. "Convergence of gradient method with momentum for back-propagation neural networks." Journal of computational mathematics (2008): 613-623.](https://www.global-sci.org/v1/jcm/volumes/v26n4/pdf/264-613.pdf)

这两篇论文是讨论自适应动量项和带动量项BP神经网络的收敛性，不同的论文，算法细节也有不同，我只是实现了最基础的动量项。

**Comment by liangjiayy** [comment]
好的，已经看到了，在第二篇文章的615页里面
